# Advanced Armor by iLucaH
# Please if you encounter any issues, report it
# Discord: https://discord.gg/GquPc7h
# Wiki: https://github.com/iLucaH/AdvancedArmor/wiki
# Config Info: https://github.com/iLucaH/AdvancedArmor/wiki/Documented-config
####################################################################################
#                                                                                  #
# IMPORTANT: Please refrain from reloading the plugin. Reload the server instead.  #
# Boost Plugins are only reloaded when the server is reloaded!                     #
#                                                                                  #
####################################################################################

Money-Armor:
  Economy-Dependencies:
    Essentials-Enabled: false
    ShopGUIPlus-Enabled: false
    UltraBackpacks-Enabled: false
    ClipAutoSell-Enabled: false
    DeluxeSellWands-Enabled: false
    Scyther-Enabled: false
    EconomyShopGUI-Enabled: false
    WildTools-Enabled: false
Coin-Armor:
  Economy-Dependencies:
    SuperMobCoins-Enabled: false
    TMMobcoins-Enabled: false
Token-Armor:
  Economy-Dependencies:
    DeluxeSellWands-Enabled: false
    RevEnchants-Enabled: false
Gem-Armor:
  Economy-Dependencies:
    RevEnchants-Enabled: false
Translations:
  Helmet: 'Helmet'
  Chestplate: 'Chestplate'
  Leggings: 'Leggings'
  Boots: 'Boots'
  Placeholders:
    No-Armor-Equipped: '&cNo Armor Equipped!'

# For developers. Remember to enable 'Enabled' AND 'Console' or 'Player'.
Debug:
  Enabled: false
  Console: false
  Player: false